# Generated by Django 5.1.3 on 2025-04-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=69)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.IntegerField(null=True)),
                ("password", models.CharField(max_length=69)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=69
                    ),
                ),
                ("address", models.CharField(max_length=200)),
            ],
        ),
    ]
