# Generated by Django 5.1.3 on 2025-05-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Eshoppy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("electronics", "ELECTRONICS"),
                            ("clothing", "CLOTHING"),
                            ("books", "BOOKS"),
                            ("furniture", "FURNITURE"),
                            ("food", "FOOD"),
                        ],
                        max_length=50,
                    ),
                ),
                ("photo", models.FileField(blank=True, null=True, upload_to="photo/")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("availability", models.BooleanField(default=True)),
            ],
        ),
    ]
