# Generated by Django 5.1.3 on 2025-05-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Eshoppy", "0003_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
